### PR TITLE
update spring dependencies

### PR DESCRIPTION
**Pull request by xurror**

### CODE REVIEW

**Comment by xurror** [comment]
@aasaru

**Comment by aasaru** [comment]
Hi @xurror 
As you are now Apache Committer and once you have connected your github account with Apache organization you should be able to directly commit into 
github.com/apache/fineract* branches (except for main branch 'develop').

So if you get this working then feel free to push your code to 
github.com/apache/finerac-cn-* branches of spring_boot_2
Once you have completed migration to spring boot 2 on all repositories then we have one grand code review and some testing before we migrate everything on spring_boot_2 branches to develop branch.

Feel free to reach out if you have any problems connecting your github account or figuring out how to push directly to apache/fineract* repos

**Comment by xurror** [comment]
Ok, thanks for the update. I'll try that now.

**Comment by xurror** [comment]
Ok, Seems my permissions have not been granted yet. Please how do i proceed to connect my account?

**Comment by aasaru** [comment]
I updated the instructions here:
https://cwiki.apache.org/confluence/display/FINERACT/Contributing+to+Apache+Fineract+as+committer
Please follow and if there is anything missing please let me know or edit the instructions directly.

**Comment by xurror** [comment]
Ok, thank you.

**Comment by xurror** [comment]
Works now. Should be able to update faster from now on.

**Pull request merged**
