### PR TITLE
Support for secured MQ

### PR DESCRIPTION
**Pull request by rverma-jm**
Bumped mq and support for authentication. Required is we are using Amazon MQ

### CODE REVIEW

**Comment by rverma-jm** [comment]
@aasaru Can you please review and merge this.

**Comment by awasum** [comment]
Why dont we make securing the MQ optional? such that, if the username and password for activeMQ are available, we use them to set the proper fields. But if the username and password are not in the environment, we dont set the username and password for activeMQ. 

What do you all think? Backward compatible and ease testing.

**Comment by rverma-jm** [comment]
updated

**Comment by awasum** [comment]
LGTM

**Comment by rverma-jm** [comment]
@awasum I am looking forward to contribute the update of gradle, spring-boot and spring-cloud for our internal usage.  Would love to send PR for upstream.

Few additional things I want is to migrate the service discovery and config management to kubernetes native. https://cloud.spring.io/spring-cloud-kubernetes/reference/html/.

Will you accept pull requests for same?

**Comment by awasum** [comment]
> @awasum I am looking forward to contribute the update of gradle, spring-boot and spring-cloud for our internal usage. Would love to send PR for upstream.
> 
> Few additional things I want is to migrate the service discovery and config management to kubernetes native. https://cloud.spring.io/spring-cloud-kubernetes/reference/html/.
> 
> Will you accept pull requests for same?

Yes, propose your changes by send a PR. Also sign up to the mailing list and discuss your ideas. It will be great to have contributions from you. https://mifos.org/resources/community/communications/

Introduce yourself when you signup to the Fineract Dev List.

Thanks very much for your work.

**Pull request merged**
